name: ZMediumToMarkdown2

on:
  workflow_dispatch:  # This allows manual triggering only

jobs:
  sync-medium-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./  # Assumes the action is in the root of your repo
        with:
          command: '-p https://readmedium.com/%E5%A6%82%E4%BD%95%E7%94%A8-vosviewer-%E5%88%86%E6%9E%90-cnki-%E6%95%B0%E6%8D%AE-1e86785df7ff'  # Replace with your Medium publication URL
